/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
    interface AppHome {}
    interface AppRoot {}
    interface NwMember {
        memberId: number;
    }
    interface NwMembers {
        name: string;
    }
    interface WarAttendance {
        name: string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLNwMemberElement extends Components.NwMember, HTMLStencilElement {}
    var HTMLNwMemberElement: {
        prototype: HTMLNwMemberElement;
        new (): HTMLNwMemberElement;
    };
    interface HTMLNwMembersElement extends Components.NwMembers, HTMLStencilElement {}
    var HTMLNwMembersElement: {
        prototype: HTMLNwMembersElement;
        new (): HTMLNwMembersElement;
    };
    interface HTMLWarAttendanceElement extends Components.WarAttendance, HTMLStencilElement {}
    var HTMLWarAttendanceElement: {
        prototype: HTMLWarAttendanceElement;
        new (): HTMLWarAttendanceElement;
    };
    interface HTMLElementTagNameMap {
        'app-home': HTMLAppHomeElement;
        'app-root': HTMLAppRootElement;
        'nw-member': HTMLNwMemberElement;
        'nw-members': HTMLNwMembersElement;
        'war-attendance': HTMLWarAttendanceElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {}
    interface AppRoot {}
    interface NwMember {
        memberId?: number;
    }
    interface NwMembers {
        name?: string;
    }
    interface WarAttendance {
        name?: string;
    }
    interface IntrinsicElements {
        'app-home': AppHome;
        'app-root': AppRoot;
        'nw-member': NwMember;
        'nw-members': NwMembers;
        'war-attendance': WarAttendance;
    }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
    export namespace JSX {
        interface IntrinsicElements {
            'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            'nw-member': LocalJSX.NwMember & JSXBase.HTMLAttributes<HTMLNwMemberElement>;
            'nw-members': LocalJSX.NwMembers & JSXBase.HTMLAttributes<HTMLNwMembersElement>;
            'war-attendance': LocalJSX.WarAttendance & JSXBase.HTMLAttributes<HTMLWarAttendanceElement>;
        }
    }
}
