name: Azoth Empire Discord Bot Docker Image CI
on:
  push:
    branches: [main]
#  pull_request:
#    branches: [main]
jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image for AE Bot
        run: docker build . --file azoth-empire-bot/Dockerfile --tag bodnapa/azoth-empire-bot:${GITHUB_SHA}
      - name: Push the Docker image for AE Bot
        run: docker push bodnapa/azoth-empire-bot:${GITHUB_SHA}
  build-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image for AE Webapp
        run: docker build . --file azoth-empire-ui/Dockerfile --tag bodnapa/azoth-empire-web-app:${GITHUB_SHA}
      - name: Push the Docker image for AE Webapp
        run: docker push bodnapa/azoth-empire-web-app:${GITHUB_SHA}
