on:
  release:
    types: [published]
name: Azoth Empire Discord Bot Docker Image CI
jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Log in to Docker Hub
        uses: docker/login-action@f6d32ad0236599ffe0bb261e71184c3e4e1d47cd
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image for AE Bot
        run: |
          cd azoth-empire-bot && \
          docker build --tag bodnapa/azoth-empire-bot:${GITHUB_SHA::8} --tag bodnapa/azoth-empire-bot:${GITHUB_REF:10} --tag bodnapa/azoth-empire-bot:latest .
      - name: Push the Docker image for AE Bot
        run: docker push --all-tags bodnapa/azoth-empire-bot
