name: Azoth Empire Discord Bot Docker Image CI
on:
  push:
    branches: [main]
#  pull_request:
#    branches: [main]
jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image for AE Bot
        run: |
          cd azoth-empire-bot && \
          docker build --tag bodnapa/azoth-empire-bot:${GITHUB_SHA::8} --tag bodnapa/azoth-empire-bot:latest .
      - name: Push the Docker image for AE Bot
        run: docker push --all-tags bodnapa/azoth-empire-bot
  build-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image for AE Webapp
        run: |
          cd azoth-empire-ui && \
          docker build --tag bodnapa/azoth-empire-web-app:${GITHUB_SHA::8} --tag bodnapa/azoth-empire-web-app:latest .
      - name: Push the Docker image for AE Webapp
        run: docker push --all-tags bodnapa/azoth-empire-web-app
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image for AE API
        run: |
          cd azoth-empire-api && \
          docker build --tag bodnapa/azoth-empire-graphql-api:${GITHUB_SHA::8} --tag bodnapa/azoth-empire-graphql-api:latest .
      - name: Push the Docker image for AE API
        run: docker push --all-tags bodnapa/azoth-empire-graphql-api
