name: Azoth Empire Discord Bot Docker Image CI
on:
  push:
        branches: [main]
jobs:
  run-semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Run Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.AE_GITHUB_TOKEN }}
        run: npx semantic-release
