on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
name: Azoth Empire Webapp Docker Image CI
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image for AE Webapp
        run: |
          cd azoth-empire-ui && \
          docker build --tag bodnapa/azoth-empire-web-app:${GITHUB_SHA::8} --tag bodnapa/azoth-empire-web-app:${GITHUB_REF} --tag bodnapa/azoth-empire-web-app:latest .
      - name: Push the Docker image for AE Webapp
        run: docker push --all-tags bodnapa/azoth-empire-web-app
